CREATE TABLE PLAYERDETAILS(
	PLAYER_ID INT PRIMARY KEY,
	COUNTRY_ID INT,
	TEAM_ID INT,
	PLAYER_FIRST_NAME VARCHAR(20) NOT NULL,
	PLAYER_SECOND_NAME VARCHAR(20)  NOT NULL,
	PLAYER_DOB DATE NOT NULL,
--	AGE INT GENERATED ALWAYS AS (EXTRACT(YEAR FROM AGE(DOB))) STORED,
	PLAYER_ROLE VARCHAR(50),
	BATTING_ARM VARCHAR(10),
	BOWLING_ARM VARCHAR(10),
	BOWLING_TYPE VARCHAR(20),
	RETIRED VARCHAR(5)
);

CREATE TABLE COUNTRIES(
	COUNTRY_ID INT PRIMARY KEY,
	COUNTRY_NAME VARCHAR(50)
);

CREATE TABLE TEAMS(
	TEAM_ID INT PRIMARY KEY,
	TEAM_NAME VARCHAR(50)
);

CREATE TABLE FORMATS(
	FORMAT_ID INT PRIMARY KEY,
	FORMAT_NAME VARCHAR(20)
);

CREATE TABLE TOURNAMENTS(
	TOURNAMENT_ID INT PRIMARY KEY,
	TOURNAMENT_NAME VARCHAR(50),
	TOURNAMENT_HOST INT,
	TOURNAMENT_SEASON INT,
	TOURNAMENT_YEAR DATE
);

CREATE TABLE SEASON(
	SEASON_ID INT PRIMARY KEY,
	SEASON_YEAR DATE
);

CREATE TABLE GROUND(
	GROUND_ID INT PRIMARY KEY,
	GROUND_NAME VARCHAR(50),
	GROUND_COUNTRY INT
);

CREATE TABLE MATCHES(
	MATCH_ID INT PRIMARY KEY,
	TEAM_ONE INT,
	TEAM_TWO INT,
	MATCH_GROUND VARCHAR(50),
	MATCH_COUNTRY VARCHAR(50),
	TOSS_WINNER INT,
	BAT_FIRST INT,
	BAT_SECOND INT,
	BAT_FIRST_SCORE INT,
	BAT_SECOND_SCORE INT,
	MATCH_WINNER INT,
	TEAM_ONE_PLAYERS VARCHAR(1000),
	TEAM_TWO_PLAYERS VARCHAR(1000)
);